name: fyp
dependencies:
- backports_abc=0.4=py34_0
- pip=8.1.2=py34_0
- python=3.4.5=0
- setuptools=25.1.6=py34_0
- tornado=4.3=py34_0
- vs2010_runtime=10.00.40219.1=2
- wheel=0.29.0=py34_0
- pip:
  - backports-abc==0.4
  - decorator==4.0.9
  - flask==0.10.1
  - itsdangerous==0.24
  - jinja2==2.8
  - jsonpickle==0.9.3
  - markupsafe==0.23
  - networkx==1.11
  - nose==1.3.7
  - psutil==4.3.1
  - ujson==1.35
  - werkzeug==0.11.9

