version: 2

# Based on https://circleci.com/docs/2.0/language-python/#full-configuration-file
jobs:
  build:
    docker:
      - image: circleci/python:3.4.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.4/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}
          # deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.4/site-packages"
      - run:
          command: |
            pipenv run python -m unittest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
